language: node_js 
node_js: 8

before_install:
- export TZ='Asia/Shanghai'
install:
- npm install -g hexo-cli
- npm install -g hexo-deployer-git
- npm install -g gulp
- npm install

script:
- hexo g
- gulp
- hexo d

branches:
  only:
  - hexo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  repo: vtnil/vtnil.github.io
  target_branch: master
  on:
    branch: hexo
