language: node_js 
node_js: 8

before_install:
  - export TZ='Asia/Shanghai'
install:
  - npm install -g hexo-cli
  - npm install -g gulp
  - npm install
cache:
  directories:
    - node_modules

script:
  - hexo clean
  - hexo generate
  - gulp

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  repo: vtnil/vtnil.github.io
  target_branch: master
  on:
    branch: hexo
